name = "saddlebag-with-pockets"
compatibility_date = "2024-11-04"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables (overridden at build time via build.sh)
DISCORD_CLIENT_ID = ""
DISCORD_CLIENT_SECRET = ""
DISCORD_BOT_TOKEN = ""

[env.production]
compatibility_date = "2024-11-04"
compatibility_flags = ["nodejs_compat"]
